### ISSUE TITLE
🔧 [기능요청][swagger] 프로젝트 기본 설정 Swagger

### ISSUE THREAD

**Issue by Chuseok22** [Team-0nePiece/DailySnap-BE#9]
📝 현재 문제점
---

- 백엔드가 사용할 수 있는 유일한(?) UI swagger입니다
- 다양한 설정을 할 수 있어요
  - JWT 토큰
  - 서버 설정
  - 카테고리 설정 등등

- 원하는 디자인 및 기능들로 이쁘게 꾸며주세요~

### 개발 순서
1. build.gradle swagger 의존성 추가 (버전 호환여부 잘 확인하세요)
2. SwaggerConfig 클래스 작성 (기본적인 swagger 설정은 해당 클래스에서 모두 진행)
3. SecurityUrl 설정 (swagger 화면은 Authorization이 없어도 접근할 수 있어야합니다)
4. 경로는 `/docs/swagger` 로 설정부탁드립니다~

🛠️ 해결 방안 / 제안 기능
---
기본적인 코드를 올려줄테니까 참고해서 개발하셔도 좋습니다아~

## `SwaggerConfig`
```
package com.ticketmate.backend.util.config;

import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.info.Info;
import io.swagger.v3.oas.annotations.servers.Server;
import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.security.SecurityScheme;
import io.swagger.v3.oas.models.security.SecurityScheme.In;
import io.swagger.v3.oas.models.security.SecurityScheme.Type;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.List;

@OpenAPIDefinition(
        info = @Info(
                title = "🎫 티켓메이트 : TICKET-MATE 🎫",
                description = """
                        ### 🌐 티켓메이트 웹사이트 🌐 : ticketmate.co.kr
                        [**웹사이트 바로가기**](http://34.22.77.73:8087) 

                        ### 💻 **GitHub 저장소**
                        - **[백엔드 소스코드](https://github.com/Team-TicketMate/ticketmate-server)**
                          백엔드 개발에 관심이 있다면 저장소를 방문해보세요.
                        """,
                version = "1.0v"
        ),
        servers = {
                @Server(url = "https://34.22.77.73:8087", description = "메인 서버"),
                @Server(url = "https://34.22.77.73:8088", description = "테스트 서버"),
                @Server(url = "http://localhost:8080", description = "로컬 서버")
        }
)
@Configuration
public class SwaggerConfig {

    @Bean
    public OpenAPI openAPI() {
        SecurityScheme apiKey = new SecurityScheme()
                .type(Type.HTTP)
                .in(In.HEADER)
                .name("Authorization")
                .scheme("bearer")
                .bearerFormat("JWT");

        SecurityRequirement securityRequirement = new SecurityRequirement()
                .addList("Bearer Token");

        return new OpenAPI()
                .components(new Components().addSecuritySchemes("Bearer Token", apiKey))
                .addSecurityItem(securityRequirement)
                .servers(List.of(
                                new io.swagger.v3.oas.models.servers.Server()
                                        .url("http://localhost:8080")
                                        .description("로컬 서버"),
                                new io.swagger.v3.oas.models.servers.Server()
                                        .url("http://34.22.77.73:8088")
                                        .description("테스트 서버"),
                                new io.swagger.v3.oas.models.servers.Server()
                                        .url("http://34.22.77.73:8087")
                                        .description("메인 서버")
                        )
                );
    }
}
```

## `application.yml`
```
spring:
  profiles:
    active: prod
  config:
    import:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          show_sql: true
          format_sql: true
          open-in-view: false
          use_sql_comments: true
  servlet:
    multipart:
      enabled: true # 파일 업로드 허용
      max-file-size: 200MB # 업로드 파일 최대 크기
      max-request-size: 1000MB # 요청 전체 최대 크기
      file-size-threshold: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /docs/swagger
```

🙋‍♂️ 담당자
---
- 백엔드: @nayoung04 
- 프론트엔드: 이름
- 디자인: 이름
